# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_auto_20160307_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Venue',
            field=models.CharField(choices=[(b'1', b'Pronite Area'), (b'2', b'Basket-Court'), (b'3', b'Academic Block 1'), (b'4', b'Academic Block 2'), (b'5', b'Mall Stage')], default=b'1', max_length=1),
        ),
    ]
