# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0004_auto_20160306_0839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
