# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0004_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='first_time_preference',
        ),
        migrations.AddField(
            model_name='event',
            name='first_time',
            field=models.CharField(choices=[(b'01', b'Day 1, 9:00am'), (b'02', b'Day 1, 11:00am'), (b'03', b'Day 1, 1:00pm'), (b'04', b'Day 1, 3:00pm'), (b'05', b'Day 1, 5:00pm'), (b'11', b'Day 2, 9:00am'), (b'12', b'Day 2, 11:00am'), (b'13', b'Day 2, 1:00pm'), (b'14', b'Day 2, 3:00pm'), (b'15', b'Day 2, 5:00pm')], default=b'01', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='first_time_day',
            field=models.CharField(choices=[(b'01', b'Day 1, 9:00am'), (b'02', b'Day 1, 11:00am'), (b'03', b'Day 1, 1:00pm'), (b'04', b'Day 1, 3:00pm'), (b'05', b'Day 1, 5:00pm'), (b'11', b'Day 2, 9:00am'), (b'12', b'Day 2, 11:00am'), (b'13', b'Day 2, 1:00pm'), (b'14', b'Day 2, 3:00pm'), (b'15', b'Day 2, 5:00pm')], default=b'01', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='Venue',
            field=models.CharField(choices=[(b'1', b'Pronite Area'), (b'2', b'Basky-Court'), (b'3', b'Academic Block 1'), (b'4', b'Academic Block 2'), (b'5', b'Mall Stage')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='second_time_preference',
            field=models.CharField(choices=[(b'01', b'Day 1, 9:00am'), (b'02', b'Day 1, 11:00am'), (b'03', b'Day 1, 1:00pm'), (b'04', b'Day 1, 3:00pm'), (b'05', b'Day 1, 5:00pm'), (b'11', b'Day 2, 9:00am'), (b'12', b'Day 2, 11:00am'), (b'13', b'Day 2, 1:00pm'), (b'14', b'Day 2, 3:00pm'), (b'15', b'Day 2, 5:00pm')], default=b'02', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='third_time_preference',
            field=models.CharField(choices=[(b'01', b'Day 1, 9:00am'), (b'02', b'Day 1, 11:00am'), (b'03', b'Day 1, 1:00pm'), (b'04', b'Day 1, 3:00pm'), (b'05', b'Day 1, 5:00pm'), (b'11', b'Day 2, 9:00am'), (b'12', b'Day 2, 11:00am'), (b'13', b'Day 2, 1:00pm'), (b'14', b'Day 2, 3:00pm'), (b'15', b'Day 2, 5:00pm')], default=b'03', max_length=2),
        ),
    ]
