# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_auto_20160306_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuserregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.Profile'),
        ),
    ]
