# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0008_auto_20160307_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Actual_time',
            field=models.CharField(choices=[(b'0', b'Day 1'), (b'1', b'Day 2'), (b'2', b'Day 3'), (b'3', b'Day 4')], default=b'0', max_length=1, null=True),
        ),
    ]
